repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: Max File Size
        args: ['--maxkb=2048']
        description: "Ensure files are not larger than 2MB"

      - id: check-merge-conflict
        name: Unresolved Conflicts
        description: "Ensure there are no merge conflicts in the code"

      - id: check-json
        name: Ensure JSON integrity
        description: "Ensure JSON files are valid"

